[package]
name = "skins"
version = "0.1.0"
authors = ["Tim203"]

[lib]
name = "skins"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.22.0-rc.0"
lodepng = "3.4.3"
jsonwebtokens = "1.0.0-alpha.13"
serde_json = "1.0.61"